[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#424242"
blue = "#54A4F3"
cyan = "#26BBD1"
green = "#7ABA3A"
magenta = "#AA4DBC"
red = "#E83B3F"
white = "#D9D9D9"
yellow = "#FFEA2E"

[colors.normal]
black = "#212121"
blue = "#134EB2"
cyan = "#0E717C"
green = "#457B24"
magenta = "#560088"
red = "#B7141F"
white = "#EFEFEF"
yellow = "#F6981E"

[colors.primary]
background = "#111111"
foreground = "#E5E5E5"

[font]
size = 16

[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true

[shell]
program = "/usr/bin/bash"

[window]
opacity = 0.8

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 5
y = 5
